### ISSUE TITLE
Compile error: ordinal type expected

### ISSUE THREAD

**Issue by recoilme** [SPY/nim-memcached#1]
Hi 
Then i try compile with 0.15.0 version i get error:

netdef.nim(85, 32) Error: ordinal type expected
self.`capFieldName` = ord(value).`fieldType`.hostToNet()

May you please explain whats wrong here?

**Comment by SPY** [comment]
Hi.
uint64 is not ordinal already.
I have small DSL for creating network serialisable structures and it treats uint64 as ordinal.
Memcached's request and response headers have field `pub cas: uint64`.
I will fix it soon.

**Comment by SPY** [comment]
fixed
